trigger:
- '*'
 
pr:
- '*'
 
jobs:
- job: Build
  displayName: 'Build Job'
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
 
  - script: |
      choco install unreal-linux-toolchain
    displayName: 'Install Unreal Engine 5.1'
 
  - script: |
      setx UE_ROOT "C:\Program Files\Epic Games\UE_5.1" /M
    displayName: 'Set Unreal Engine 5.1 Root'
 
  - script: |
      C:\JenkinsBuildDirectory\Batch\TestBatch.bat
    displayName: 'Run custom batch script'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'