trigger:
  branches:
    exclude:
      - '*'
 
pr:
  branches:
    exclude:
      - '*'
 
jobs:
- job: Build
  displayName: 'Build Job'
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
 
  - script: |
      choco install ue4
    displayName: 'Install Unreal Engine'
 
  - script: |
      ue4 setroot C:\Program Files\Epic Games\UE_4.26
    displayName: 'Set Unreal Engine Root'
 
  - script: |
      ue4 package project -pak -targetplatform=Win64 -clientconfig=Development -serverconfig=Development -archive -archivedirectory=$(Build.ArtifactStagingDirectory)
    displayName: 'Build UE Project'
 
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'